# labeler.yml

# 针对 Pull Request 的规则
pull_requests:
  - name: "bug"          # 标签名称
    patterns:
      - "fix*"           # 匹配标题或内容包含 "fix" 字样的 PR

  - name: "enhancement"
    patterns:
      - "feature*"

# 针对 Issues 的规则
issues:
  - name: "documentation"
    patterns:
      - "docs*"
      - "readme"

  - name: "question"
    patterns:
      - "help*"
      - "question"
