name: 🧪 CI Codecov
on: 
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

permissions:
    contents: read
    pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        # TODO: cross fork PR will not trigger this action
        - name: 🧬 Report coverage
          uses: codecov/codecov-action@v4.0.1
          env:
              CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}